name: RandomItems
version: ${project.version}
main: dev.kalonic.randomitems.Main
api-version: 1.16
authors: [ Kalonic ]
description: Gives you a random item every 30 seconds.
commands:
  randomitems:
    aliases: [ri]